"""Field-name sanitation and schema normalization for dynamic extraction.

The extraction schema is generated by an LLM at query time and is therefore
**untrusted input** (Req 8.3). Everything in this module is written to be safe
to apply to arbitrary strings and arbitrary field collections: invalid, empty,
and duplicate field names are dropped, the number of dynamic fields is bounded
by a configurable cap (Req 8.2), and a fixed core of comparable fields is always
merged in regardless of what the LLM proposed (Req 3.1).

The computed ``schema_version`` is derived purely from the field set and is
independent of any model name (Req 7.2), so the schema can evolve separately
from the extraction model.
"""
from __future__ import annotations

import hashlib
import json
import re
from typing import Any, Iterable, Literal, Optional

from pydantic import BaseModel, Field, create_model

from app.models.schemas import ExtractionField, ExtractionSchema

# Maximum length of a sanitized field name. Bounds token cost and keeps names
# usable as Pydantic field identifiers downstream.
MAX_FIELD_NAME_LENGTH = 64

# Maximum length of a field description. Descriptions are LLM-generated and get
# injected verbatim into the extraction system prompt, so an unbounded (or
# adversarial) description could blow the model's context budget. Truncating
# here bounds prompt size without affecting normal descriptions (Req 8.2, 8.3).
MAX_FIELD_DESCRIPTION_LENGTH = 256

# Allowed field types (mirrors ExtractionField.type).
ALLOWED_TYPES = ("string", "number", "boolean", "enum")

# The fixed core fields that ranking/comparison depend on. These are always
# merged as is_core=True regardless of the LLM-proposed schema (Req 3.1) and are
# never subject to the dynamic-field cap.
CORE_FIELDS: tuple[tuple[str, str], ...] = (
    ("price", "number"),
    ("availability", "boolean"),
    ("negotiated", "boolean"),
)

CORE_FIELD_NAMES = frozenset(name for name, _ in CORE_FIELDS)

# Matches a fully-valid sanitized identifier.
_VALID_NAME_RE = re.compile(r"^[a-z0-9_]+$")
# Runs of characters that are NOT part of a valid identifier.
_INVALID_RUN_RE = re.compile(r"[^a-z0-9]+")


def sanitize_field_name(raw: Any) -> str | None:
    """Turn an arbitrary/untrusted value into a safe snake_case identifier.

    Returns a string matching ``^[a-z0-9_]+$`` (bounded length), or ``None`` when
    the input is empty/invalid or sanitizes down to nothing.

    The function is idempotent: ``sanitize_field_name(sanitize_field_name(x))``
    equals ``sanitize_field_name(x)`` for every input.
    """
    if not isinstance(raw, str):
        return None

    # Lowercase, then collapse every run of non-identifier characters (including
    # underscores and whitespace) into a single underscore.
    lowered = raw.strip().lower()
    collapsed = _INVALID_RUN_RE.sub("_", lowered)

    # Bound the length before trimming so a truncation that lands on an
    # underscore is cleaned up by the trailing-strip below.
    truncated = collapsed[:MAX_FIELD_NAME_LENGTH]

    # Drop leading/trailing underscores so the result is a clean fixed point.
    cleaned = truncated.strip("_")

    if not cleaned:
        return None
    return cleaned


def _coerce_get(field: Any, key: str) -> Any:
    """Read ``key`` from a dict or an attribute from an object, untrusted-safe."""
    if isinstance(field, dict):
        return field.get(key)
    return getattr(field, key, None)


def _coerce_type(raw_type: Any, enum_values: list[str] | None) -> str:
    """Validate the field type, defaulting safely for untrusted input."""
    if isinstance(raw_type, str):
        lowered = raw_type.strip().lower()
        if lowered in ALLOWED_TYPES:
            # An "enum" with no usable values degrades to a plain string.
            if lowered == "enum" and not enum_values:
                return "string"
            return lowered
    return "string"


def _coerce_enum_values(raw: Any) -> list[str] | None:
    """Coerce enum values into a clean, de-duplicated list of strings."""
    if not isinstance(raw, (list, tuple)):
        return None
    seen: set[str] = set()
    values: list[str] = []
    for item in raw:
        if not isinstance(item, str):
            continue
        text = item.strip()
        if not text or text in seen:
            continue
        seen.add(text)
        values.append(text)
    return values or None


def _schema_version(fields: list[ExtractionField]) -> str:
    """Compute a model-independent, set-stable schema version.

    The hash is taken over a canonical, order-independent representation of the
    field set so the same set of fields always yields the same version,
    regardless of input order or the model used to generate it (Req 7.2).
    """
    canonical = sorted(
        [
            [f.name, f.type, bool(f.is_core), sorted(f.enum_values or [])]
            for f in fields
        ]
    )
    digest = hashlib.sha256(
        json.dumps(canonical, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    ).hexdigest()
    return f"v1-{digest[:12]}"


def normalize_schema(
    raw_fields: Iterable[Any] | None,
    *,
    max_fields: int,
) -> ExtractionSchema:
    """Normalize an untrusted LLM-proposed field list into an ``ExtractionSchema``.

    - ``raw_fields`` may be a list of dicts (``name``/``type``/``description``/
      ``enum_values``) or ``ExtractionField``-like objects.
    - Invalid, empty, and duplicate field names (after sanitation) are dropped.
    - Names colliding with a core field are dropped (the core field wins).
    - Dynamic (non-core) fields are capped at ``max_fields``.
    - The three core fields (``price``/``availability``/``negotiated``) are always
      merged as ``is_core=True`` and are never truncated.
    """
    cap = max(0, int(max_fields))

    dynamic_fields: list[ExtractionField] = []
    seen_names: set[str] = set(CORE_FIELD_NAMES)

    for raw in raw_fields or []:
        if len(dynamic_fields) >= cap:
            break

        name = sanitize_field_name(_coerce_get(raw, "name"))
        if name is None or name in seen_names:
            continue

        enum_values = _coerce_enum_values(_coerce_get(raw, "enum_values"))
        field_type = _coerce_type(_coerce_get(raw, "type"), enum_values)
        if field_type != "enum":
            enum_values = None

        description = _coerce_get(raw, "description")
        if not isinstance(description, str) or not description.strip():
            description = None
        else:
            # Bound the description length: it is LLM-generated and injected
            # verbatim into the extraction prompt, so cap it to keep prompt size
            # bounded (Req 8.2, 8.3).
            description = description.strip()[:MAX_FIELD_DESCRIPTION_LENGTH]

        seen_names.add(name)
        dynamic_fields.append(
            ExtractionField(
                name=name,
                type=field_type,
                description=description,
                enum_values=enum_values,
                is_core=False,
            )
        )

    core_fields = [
        ExtractionField(name=name, type=field_type, is_core=True)
        for name, field_type in CORE_FIELDS
    ]

    fields = core_fields + dynamic_fields
    return ExtractionSchema(schema_version=_schema_version(fields), fields=fields)


# --------------------------------------------------------------------------
# Dynamic Pydantic model builder (Req 3.1, 3.4, 4.2)
# --------------------------------------------------------------------------

# Maps an ExtractionField primitive type to the Python type used for parsing.
_PRIMITIVE_TYPE_MAP: dict[str, type] = {
    "string": str,
    "number": float,
    "boolean": bool,
}

# The core fields have FIXED Python types regardless of what the schema claims,
# because ranking/comparison downstream depends on these exact shapes (Req 3.1).
_CORE_TYPE_MAP: dict[str, type] = {
    "price": float,
    "availability": bool,
    "negotiated": bool,
}


def _python_type_for(field: ExtractionField) -> Any:
    """Resolve the Python/typing annotation used to validate ``field``.

    - Core fields use their fixed types (``price`` -> float, ``availability`` ->
      bool, ``negotiated`` -> bool) regardless of the declared type (Req 3.1).
    - ``enum`` fields become a constrained ``Literal`` over their ``enum_values``
      so out-of-set values are rejected by validation; if no usable values are
      present we fall back to ``str`` (mirrors ``normalize_schema``) (Req 4.2).
    - Other dynamic fields map by their declared type, defaulting to ``str``.
    """
    if field.is_core and field.name in _CORE_TYPE_MAP:
        return _CORE_TYPE_MAP[field.name]

    if field.type == "enum":
        values = [v for v in (field.enum_values or []) if isinstance(v, str) and v]
        if values:
            return Literal[tuple(values)]  # type: ignore[valid-type]
        return str

    return _PRIMITIVE_TYPE_MAP.get(field.type, str)


def build_dynamic_model(schema: ExtractionSchema) -> type[BaseModel]:
    """Build a Pydantic model from an ``ExtractionSchema`` (Req 4.2).

    The resulting model:

    - Has the CORE fields (``price``/``availability``/``negotiated``) as
      REQUIRED with their fixed types (Req 3.1). Constructing an instance
      without them raises ``ValidationError``.
    - Has DYNAMIC (non-core) fields as OPTIONAL with a ``None`` default, typed
      per their ``ExtractionField.type`` (Req 3.4). Omitting them validates fine.
    - Constrains ``enum`` fields to their ``enum_values`` via ``typing.Literal``
      so out-of-set values are rejected (Req 4.2).

    ``create_model`` (Pydantic v2) is used to construct the model dynamically.
    """
    field_defs: dict[str, tuple[Any, Any]] = {}

    for field in schema.fields:
        py_type = _python_type_for(field)
        if field.is_core:
            field_defs[field.name] = (
                py_type,
                Field(..., description=field.description),
            )
        else:
            field_defs[field.name] = (
                Optional[py_type],
                Field(default=None, description=field.description),
            )

    # Stable, sensible model name derived from the model-independent version.
    safe_version = re.sub(r"[^0-9a-zA-Z_]", "_", schema.schema_version)
    model_name = f"DynamicExtraction_{safe_version}"

    return create_model(model_name, **field_defs)
